homepage:
  url:    /
  param:  { module: sitioWeb, action: index, format: html }

adminHomepage:
  url:    /admin
  param:  { module: sitioWeb, action: admin, format: html }

shfSecurity_index:
  url:    /signin
  param:  { module: shfSecurity, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

shfSecurity_login:
  url:    /login
  param:  { module: shfSecurity, action: login, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    - model/base/usuarioCredencialBaseTableClass.php
    - model/usuarioCredencialTableClass.php
    - model/base/credencialBaseTableClass.php
    - model/credencialTableClass.php
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_logout:
  url:    /logout
  param:  { module: shfSecurity, action: logout, format: html }
  load:
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_noPermission:
  url:    /sin_permisos
  param:  { module: shfSecurity, action: noPermission, format: html }

shfSecurity_exception:
  url:    /exception
  param:  { module: shfSecurity, action: exception, format: html }




#
# __________________________cliente___________________
cliente_cliente:
  url:   /cliente
  param:  { module: cliente, action: cliente, format: html }
  load:
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php

cliente_cliente_create:
  url:    /cliente/crear/cliente
  param:  { module: cliente, action: createCliente, format: html }
  load:
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php
    - libs/validator/cliente/clienteValidatorClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php

cliente_edit:
  url:    /cliente/edit
  param:  { module: cliente, action: editCliente, format: html }
  load:
   - model/base/clienteBaseTableClass.php
   - model/clienteTableClass.php
   - model/base/tipo_documentoBaseTableClass.php
   - model/tipo_documentoTableClass.php
   - model/base/localidadBaseTableClass.php
   - model/localidadTableClass.php

cliente_update:
  url:    /cliente/update
  param:  { module: cliente, action: updateCliente, format: html }
  load:
   - model/base/clienteBaseTableClass.php
   - model/clienteTableClass.php

cliente_delete:
  url:    /cliente/delete
  param:  { module: cliente, action: delete, format: html }
  load:
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php

# ____________________________codeudor__________________
codeudor_codeudor:
  url:    /codeudor
  param:  { module: codeudor, action: codeudor, format: html }
  load:
    - model/base/codeudorBaseTableClass.php
    - model/codeudorTableClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php

codeudor_codeudor_create:
  url:    /codeudor/crear/codeudor
  param:  { module: codeudor, action: createCodeudor, format: html }
  load:
    - model/base/codeudorBaseTableClass.php
    - model/codeudorTableClass.php
    - libs/validator/codeudor/codeudorValidatorClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php
    
codeudor_listado:
  url:    /codeudor/listado
  param:  { module: codeudor, action: listado, format: html }
  load:
    - model/base/codeudorBaseTableClass.php
    - model/codeudorTableClass.php
   
codeudor_edit:
  url:    /codeudor/edit
  param:  { module: codeudor, action: editCodeudor, format: html }
  load:
   - model/base/codeudorBaseTableClass.php
   - model/codeudorTableClass.php
   - model/base/tipo_documentoBaseTableClass.php
   - model/tipo_documentoTableClass.php
   - model/base/localidadBaseTableClass.php
   - model/localidadTableClass.php

codeudor_update:
  url:    /codeudor/update
  param:  { module: codeudor, action: updateCodeudor, format: html }
  load:
   - model/base/codeudorBaseTableClass.php
   - model/codeudorTableClass.php
   
codeudor_delete:
  url:    /codeudor/delete
  param:  { module: cliente, action: delete, format: html }
  load:
   - model/base/codeudorBaseTableClass.php
   - model/codeudorTableClass.php
# ____________________________empleado___________________
empleado_empleado:
  url:   /empleado
  param:  { module: empleado, action: empleado, format: html }
  load:
    - model/base/empleadoBaseTableClass.php
    - model/empleadoTableClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php

empleado_empleado_create:
  url:    /empleado/crear/empleado
  param:  { module: empleado, action: createEmpleado, format: html }
  load:
    - model/base/empleadoBaseTableClass.php
    - model/empleadoTableClass.php
    - model/base/tipo_documentoBaseTableClass.php
    - model/tipo_documentoTableClass.php
    - libs/validator/empleado/empleadoValidatorClass.php
empleado_listado:
  url:    /empleado/listado
  param:  { module: empleado, action: listado, format: html }
  load:
    - model/base/empleadoBaseTableClass.php
    - model/empleadoTableClass.php
    
    

empleado_edit:
  url:    /empleado/edit
  param:  { module: empleado, action: editEmpleado, format: html }
  load:
   - model/base/empleadoBaseTableClass.php
   - model/empleadoTableClass.php
   - model/base/tipo_documentoBaseTableClass.php
   - model/tipo_documentoTableClass.php
   
  

empleado_update:
  url:    /empleado/update
  param:  { module: empleado, action: updateEmpleado, format: html }
  load:
   - model/base/empleadoBaseTableClass.php
   - model/empleadoTableClass.php
   
empleado_delete:
  url:    /empleado/delete
  param:  { module: empleado, action: delete, format: html }
  load:
   - model/base/empleadoBaseTableClass.php
   - model/empleadoTableClass.php
    
#    ___________________negocio____________
negocio_negocio:
  url:    /negocio
  param:  { module: negocio, action: negocio, format: html }
  load:
    - model/base/negocioBaseTableClass.php
    - model/negocioTableClass.php
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php

negocio_negocio_create:
  url:    /negocio/crear/negocio
  param:  { module: negocio, action: createNegocio, format: html }
  load:
    - model/base/negocioBaseTableClass.php
    - model/negocioTableClass.php
    - libs/validator/negocio/negocioValidatorClass.php
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php
negocio_listado:
  url:    /negocio/listado
  param:  { module: negocio, action: listado, format: html }
  load:
    - model/base/negocioBaseTableClass.php
    - model/negocioTableClass.php
    
negocio_edit:
  url:    /negocio/edit
  param:  { module: negocio, action: editNegocio, format: html }
  load:
   - model/base/negocioBaseTableClass.php
   - model/negocioTableClass.php
   
  

negocio_update:
  url:    /negocio/update
  param:  { module: negocio, action: updateNegocio, format: html }
  load:
   - model/base/negocioBaseTableClass.php
   - model/negocioTableClass.php
   
negocio_delete:
  url:    /negocio/delete
  param:  { module: negocio, action: delete, format: html }
  load:
   - model/base/negocioBaseTableClass.php
   - model/negocioTableClass.php
# ________________________________banco_____________________________________________
banco:
  url: /banco
  param:  { module: banco, action: banco, format: html }
  load:
    - model/base/bancoBaseTableClass.php
    - model/bancoTableClass.php

banco_banco_create:
  url:    /banco/crear/banco
  param:  { module: banco, action: createBanco, format: html }
  load:
    - model/base/bancoBaseTableClass.php
    - model/bancoTableClass.php
    - libs/validator/banco/bancoValidatorClass.php

banco_index:
  url:    /banco/index
  param:  { module: banco, action: index, format: html }
  load:
    - model/base/bancoBaseTableClass.php
    - model/bancoTableClass.php

banco_edit:
  url:    /banco/edit
  param:  { module: banco, action: editBanco, format: html }
  load:
   - model/base/bancoBaseTableClass.php
   - model/bancoTableClass.php

banco_update:
  url:    /banco/update
  param:  { module: banco, action: updateBanco, format: html }
  load:
   - model/base/bancoBaseTableClass.php
   - model/bancoTableClass.php

banco_delete:
  url:    /banco/delete
  param:  { module: banco, action: delete, format: html }
  load:
   - model/base/bancoBaseTableClass.php
   - model/bancoTableClass.php
   
   
#   _________________________barrio__________________
barrio:
  url: /barrio
  param:  { module: barrio, action: barrio, format: html }
  load:
    - model/base/barrioBaseTableClass.php
    - model/barrioTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php

barrio_barrio_create:
  url:    /barrio/crear/barrio
  param:  { module: barrio, action: createBarrio, format: html }
  load:
    - model/base/barrioBaseTableClass.php
    - model/barrioTableClass.php
    - model/base/localidadBaseTableClass.php
    - model/localidadTableClass.php
    - libs/validator/barrio/barrioValidatorClass.php
# ___________________________________cliente_______________________________
cliente_lista:
  url:    /cliente/index
  param:  { module: cliente, action: lista, format: html }
  load:
    - model/base/clienteBaseTableClass.php
    - model/clienteTableClass.php

    