--
-- PostgreSQL database dump
--

-- Dumped from database version 9.4.1
-- Dumped by pg_dump version 9.4.1
-- Started on 2015-07-29 21:33:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 206 (class 3079 OID 11855)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2240 (class 0 OID 0)
-- Dependencies: 206
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 172 (class 1259 OID 16908)
-- Name: barrio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE barrio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE barrio_id_seq OWNER TO postgres;

--
-- TOC entry 2241 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE barrio_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE barrio_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 189 (class 1259 OID 16942)
-- Name: barrio; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE barrio (
    id integer DEFAULT nextval('barrio_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre_barrio character varying(50) NOT NULL,
    localidad_id integer
);


ALTER TABLE barrio OWNER TO postgres;

--
-- TOC entry 2242 (class 0 OID 0)
-- Dependencies: 189
-- Name: COLUMN barrio.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN barrio.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 184 (class 1259 OID 16932)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2243 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 190 (class 1259 OID 16950)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id integer DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    fecha timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    accion character varying(50) NOT NULL,
    observacion character varying(1024),
    tabla character varying(65) NOT NULL,
    registro bigint
);


ALTER TABLE bitacora OWNER TO postgres;

--
-- TOC entry 173 (class 1259 OID 16910)
-- Name: cargo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE cargo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE cargo_id_seq OWNER TO postgres;

--
-- TOC entry 2244 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE cargo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE cargo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 24576)
-- Name: cargo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE cargo (
    id integer DEFAULT nextval('cargo_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_cargo character varying(80) NOT NULL
);


ALTER TABLE cargo OWNER TO postgres;

--
-- TOC entry 2245 (class 0 OID 0)
-- Dependencies: 205
-- Name: COLUMN cargo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN cargo.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 174 (class 1259 OID 16912)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE cliente_id_seq OWNER TO postgres;

--
-- TOC entry 2246 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE cliente_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE cliente_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 191 (class 1259 OID 16968)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE cliente (
    id integer DEFAULT nextval('cliente_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    tipo_documento_id integer NOT NULL,
    numero_identificacion character varying(100) NOT NULL,
    nombre_cliente character varying(60) NOT NULL,
    apellido_cliente character varying(60) NOT NULL,
    celular_cliente character varying(12) NOT NULL,
    telefono_cliente character varying(15) NOT NULL,
    correo_cliente character varying(100) NOT NULL,
    direccion_cliente character varying(200) NOT NULL,
    fecha_nacimiento_cliente date NOT NULL,
    localidad_id integer NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE cliente OWNER TO postgres;

--
-- TOC entry 2247 (class 0 OID 0)
-- Dependencies: 191
-- Name: COLUMN cliente.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN cliente.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 175 (class 1259 OID 16914)
-- Name: codeudor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE codeudor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE codeudor_id_seq OWNER TO postgres;

--
-- TOC entry 2248 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE codeudor_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE codeudor_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 192 (class 1259 OID 16980)
-- Name: codeudor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE codeudor (
    id integer DEFAULT nextval('codeudor_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    tipo_documento_id integer NOT NULL,
    numero_identificacion integer NOT NULL,
    nombre_codeudor character varying(100) NOT NULL,
    apell_codeudor character varying(100) NOT NULL,
    telefono_codeudor character varying(15) NOT NULL,
    movil_codeudor character varying(13),
    direccion_codeudor character varying(100) NOT NULL,
    correo_codeudor character varying(60) NOT NULL,
    localidad_id integer NOT NULL
);


ALTER TABLE codeudor OWNER TO postgres;

--
-- TOC entry 2249 (class 0 OID 0)
-- Dependencies: 192
-- Name: COLUMN codeudor.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN codeudor.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 185 (class 1259 OID 16934)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2250 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 193 (class 1259 OID 16988)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id integer DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL
);


ALTER TABLE credencial OWNER TO postgres;

--
-- TOC entry 2251 (class 0 OID 0)
-- Dependencies: 193
-- Name: COLUMN credencial.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN credencial.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 176 (class 1259 OID 16916)
-- Name: empleado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE empleado_id_seq OWNER TO postgres;

--
-- TOC entry 2252 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE empleado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE empleado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 194 (class 1259 OID 16996)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empleado (
    id integer DEFAULT nextval('empleado_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL,
    apellido_empleado character varying(50) NOT NULL,
    direccion_empleado character varying(50) NOT NULL,
    telefono_empleado character varying(15) NOT NULL,
    movil_empelado character varying(12) NOT NULL,
    correo_empleado character varying(100) NOT NULL,
    cargo_id integer NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE empleado OWNER TO postgres;

--
-- TOC entry 2253 (class 0 OID 0)
-- Dependencies: 194
-- Name: COLUMN empleado.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN empleado.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 177 (class 1259 OID 16918)
-- Name: formato_de_prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE formato_de_prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE formato_de_prestamo_id_seq OWNER TO postgres;

--
-- TOC entry 2254 (class 0 OID 0)
-- Dependencies: 177
-- Name: SEQUENCE formato_de_prestamo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE formato_de_prestamo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 195 (class 1259 OID 17005)
-- Name: formato_de_prestamo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE formato_de_prestamo (
    id integer DEFAULT nextval('formato_de_prestamo_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    monto_capital integer NOT NULL,
    numero_cuotas integer NOT NULL,
    nombre_banco character varying(100) NOT NULL,
    tipo_cuenta_bancaria character varying(200) NOT NULL,
    num_cuenta_bancaria character varying(30) NOT NULL,
    cliente_id integer NOT NULL,
    codeudor_id integer NOT NULL,
    aprovado boolean DEFAULT false
);


ALTER TABLE formato_de_prestamo OWNER TO postgres;

--
-- TOC entry 2255 (class 0 OID 0)
-- Dependencies: 195
-- Name: COLUMN formato_de_prestamo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN formato_de_prestamo.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 2256 (class 0 OID 0)
-- Dependencies: 195
-- Name: COLUMN formato_de_prestamo.aprovado; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN formato_de_prestamo.aprovado IS 'FALSE = no aprovado | TRUE = aprobado';


--
-- TOC entry 178 (class 1259 OID 16920)
-- Name: localidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE localidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE localidad_id_seq OWNER TO postgres;

--
-- TOC entry 2257 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE localidad_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE localidad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 196 (class 1259 OID 17014)
-- Name: localidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE localidad (
    id integer DEFAULT nextval('localidad_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL,
    localidad_id integer
);


ALTER TABLE localidad OWNER TO postgres;

--
-- TOC entry 2258 (class 0 OID 0)
-- Dependencies: 196
-- Name: COLUMN localidad.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN localidad.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 179 (class 1259 OID 16922)
-- Name: negocio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE negocio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE negocio_id_seq OWNER TO postgres;

--
-- TOC entry 2259 (class 0 OID 0)
-- Dependencies: 179
-- Name: SEQUENCE negocio_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE negocio_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 197 (class 1259 OID 17022)
-- Name: negocio; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE negocio (
    id integer DEFAULT nextval('negocio_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre_negocio character varying(1024) NOT NULL,
    direccion_negocio character varying(100) NOT NULL,
    telefono_negocio character varying(15) NOT NULL,
    valor_ingreso_negocio numeric(12,0) NOT NULL,
    cliente_id integer NOT NULL
);


ALTER TABLE negocio OWNER TO postgres;

--
-- TOC entry 2260 (class 0 OID 0)
-- Dependencies: 197
-- Name: COLUMN negocio.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN negocio.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 180 (class 1259 OID 16924)
-- Name: paz_y_salvo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE paz_y_salvo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE paz_y_salvo_id_seq OWNER TO postgres;

--
-- TOC entry 2261 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE paz_y_salvo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE paz_y_salvo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 198 (class 1259 OID 17033)
-- Name: paz_y_salvo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE paz_y_salvo (
    id integer DEFAULT nextval('paz_y_salvo_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    valor_entregado integer NOT NULL,
    "observación" character varying(1024),
    empleado_id integer NOT NULL
);


ALTER TABLE paz_y_salvo OWNER TO postgres;

--
-- TOC entry 2262 (class 0 OID 0)
-- Dependencies: 198
-- Name: COLUMN paz_y_salvo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN paz_y_salvo.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 181 (class 1259 OID 16926)
-- Name: planilla_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE planilla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE planilla_id_seq OWNER TO postgres;

--
-- TOC entry 2263 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE planilla_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE planilla_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 199 (class 1259 OID 17044)
-- Name: planilla; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE planilla (
    id integer DEFAULT nextval('planilla_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    valor_recaudo integer NOT NULL,
    observaciones character varying(1024),
    empleado_id integer NOT NULL,
    prestamo_id integer NOT NULL
);


ALTER TABLE planilla OWNER TO postgres;

--
-- TOC entry 2264 (class 0 OID 0)
-- Dependencies: 199
-- Name: COLUMN planilla.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN planilla.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 182 (class 1259 OID 16928)
-- Name: prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE prestamo_id_seq OWNER TO postgres;

--
-- TOC entry 2265 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE prestamo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE prestamo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 200 (class 1259 OID 17055)
-- Name: prestamo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE prestamo (
    id integer DEFAULT nextval('prestamo_id_seq'::regclass) NOT NULL,
    cliente_id integer NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    formato_de_prestamo_id integer NOT NULL,
    tiempo_cuota integer NOT NULL
);


ALTER TABLE prestamo OWNER TO postgres;

--
-- TOC entry 2266 (class 0 OID 0)
-- Dependencies: 200
-- Name: COLUMN prestamo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.actived IS 'true = activo | false = inactivo';


--
-- TOC entry 2267 (class 0 OID 0)
-- Dependencies: 200
-- Name: COLUMN prestamo.tiempo_cuota; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.tiempo_cuota IS 'Cada cauntos días se recoge el dinero';


--
-- TOC entry 186 (class 1259 OID 16936)
-- Name: sesion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE sesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE sesion_id_seq OWNER TO postgres;

--
-- TOC entry 2268 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE sesion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE sesion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 17063)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id integer DEFAULT nextval('sesion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    ip_address character varying(36) NOT NULL
);


ALTER TABLE recordar_me OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 16930)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tipo_documento_id_seq OWNER TO postgres;

--
-- TOC entry 2269 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 17070)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_documento (
    id integer DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_documento character varying(100) NOT NULL
);


ALTER TABLE tipo_documento OWNER TO postgres;

--
-- TOC entry 2270 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN tipo_documento.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tipo_documento.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 188 (class 1259 OID 16940)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2271 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 17078)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id integer DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    user_name character varying(50) NOT NULL,
    password character varying(32) NOT NULL,
    last_login_at timestamp without time zone
);


ALTER TABLE usuario OWNER TO postgres;

--
-- TOC entry 2272 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 187 (class 1259 OID 16938)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2273 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 17088)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id integer DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    credencial_id integer NOT NULL
);


ALTER TABLE usuario_credencial OWNER TO postgres;

--
-- TOC entry 2217 (class 0 OID 16942)
-- Dependencies: 189
-- Data for Name: barrio; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO barrio (id, actived, created_at, deleted_at, nombre_barrio, localidad_id) VALUES (1, true, '2015-05-11 16:35:34.676', NULL, 'marroquin', NULL);
INSERT INTO barrio (id, actived, created_at, deleted_at, nombre_barrio, localidad_id) VALUES (2, true, '2015-05-11 16:37:35.464', NULL, 'manuela', NULL);
INSERT INTO barrio (id, actived, created_at, deleted_at, nombre_barrio, localidad_id) VALUES (3, true, '2015-05-11 16:37:54.638', NULL, 'puertas', NULL);


--
-- TOC entry 2274 (class 0 OID 0)
-- Dependencies: 172
-- Name: barrio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('barrio_id_seq', 3, true);


--
-- TOC entry 2218 (class 0 OID 16950)
-- Dependencies: 190
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (3, '2015-04-06 16:25:28', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (4, '2015-04-06 16:26:57', 1, 'salida del sistema', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (5, '2015-04-13 17:03:33', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (6, '2015-04-13 17:03:45', 1, 'salida del sistema', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (7, '2015-04-13 17:04:03', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (8, '2015-04-13 17:04:11', 1, 'salida del sistema', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (9, '2015-04-13 17:12:36', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (10, '2015-04-20 15:28:53', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (11, '2015-04-20 15:32:14', 1, 'salida del sistema', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (12, '2015-04-20 15:32:19', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (13, '2015-04-25 16:00:15', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (14, '2015-04-26 13:01:56', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (15, '2015-04-27 08:02:06', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (16, '2015-04-27 14:38:50', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (17, '2015-04-28 08:12:16', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (18, '2015-05-02 09:11:38', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (19, '2015-05-04 13:37:06', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (20, '2015-05-04 14:46:02', 1, 'salida del sistema', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (21, '2015-05-04 14:46:18', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (22, '2015-05-05 08:39:23', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (23, '2015-05-10 17:12:46', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (24, '2015-05-11 14:24:57', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (25, '2015-05-11 19:02:41', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (26, '2015-05-16 16:57:01', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (27, '2015-06-01 14:44:54', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (28, '2015-06-01 18:21:31', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (29, '2015-07-05 13:39:59', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (30, '2015-07-06 20:02:38', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (31, '2015-07-07 20:48:27', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (32, '2015-07-12 19:14:15', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (33, '2015-07-13 18:54:16', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (34, '2015-07-14 08:05:10', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (35, '2015-07-14 08:11:15', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (36, '2015-07-14 19:10:23', 1, 'identificación', NULL, 'NINGUNA', NULL);
INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (37, '2015-07-29 20:38:30', 1, 'identificación', NULL, 'NINGUNA', NULL);


--
-- TOC entry 2275 (class 0 OID 0)
-- Dependencies: 184
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 37, true);


--
-- TOC entry 2233 (class 0 OID 24576)
-- Dependencies: 205
-- Data for Name: cargo; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (1, true, '2015-05-04 16:40:18.525', NULL, 'julian');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (2, true, '2015-05-04 16:41:34.221', NULL, 'lasso');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (3, true, '2015-05-04 16:42:13.364', NULL, 'asdasd');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (4, true, '2015-05-04 16:44:40.394', NULL, 'andres');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (5, true, '2015-05-04 16:47:27.389', NULL, 'andres');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (6, true, '2015-05-04 16:56:38.365', NULL, 'LASSO');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (7, true, '2015-05-04 16:57:31.135', NULL, 'LASSO');
INSERT INTO cargo (id, actived, created_at, deleted_at, desc_cargo) VALUES (8, true, '2015-05-04 16:57:56.795', NULL, 'jordan');


--
-- TOC entry 2276 (class 0 OID 0)
-- Dependencies: 173
-- Name: cargo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('cargo_id_seq', 8, true);


--
-- TOC entry 2219 (class 0 OID 16968)
-- Dependencies: 191
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO cliente (id, actived, created_at, deleted_at, tipo_documento_id, numero_identificacion, nombre_cliente, apellido_cliente, celular_cliente, telefono_cliente, correo_cliente, direccion_cliente, fecha_nacimiento_cliente, localidad_id, usuario_id) VALUES (7, true, '2015-07-14 20:35:40.586', NULL, 1, '2345678', 'leonardo', 'betancourt', '234567', '234567', 'leo', 'ertyui', '2015-07-17', 5, 1);


--
-- TOC entry 2277 (class 0 OID 0)
-- Dependencies: 174
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('cliente_id_seq', 8, true);


--
-- TOC entry 2220 (class 0 OID 16980)
-- Dependencies: 192
-- Data for Name: codeudor; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2278 (class 0 OID 0)
-- Dependencies: 175
-- Name: codeudor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('codeudor_id_seq', 1, false);


--
-- TOC entry 2221 (class 0 OID 16988)
-- Dependencies: 193
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO credencial (id, actived, created_at, deleted_at, nombre) VALUES (1, true, '2015-04-06 15:36:14.496', NULL, 'admin');
INSERT INTO credencial (id, actived, created_at, deleted_at, nombre) VALUES (2, true, '2015-04-06 15:36:14.496', NULL, 'usuario');


--
-- TOC entry 2279 (class 0 OID 0)
-- Dependencies: 185
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 2, true);


--
-- TOC entry 2222 (class 0 OID 16996)
-- Dependencies: 194
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2280 (class 0 OID 0)
-- Dependencies: 176
-- Name: empleado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('empleado_id_seq', 1, false);


--
-- TOC entry 2223 (class 0 OID 17005)
-- Dependencies: 195
-- Data for Name: formato_de_prestamo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2281 (class 0 OID 0)
-- Dependencies: 177
-- Name: formato_de_prestamo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('formato_de_prestamo_id_seq', 1, false);


--
-- TOC entry 2224 (class 0 OID 17014)
-- Dependencies: 196
-- Data for Name: localidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (1, true, '2015-05-11 14:57:47', NULL, 'Colombia', NULL);
INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (5, true, '2015-05-11 15:00:01', NULL, 'Caloto', 3);
INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (6, true, '2015-05-11 15:00:23', NULL, 'Cali', 2);
INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (3, true, '2015-05-11 14:59:19', NULL, 'Cauca', 1);
INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (2, true, '2015-05-11 14:58:04', NULL, 'Valle del Cauca', 1);
INSERT INTO localidad (id, actived, created_at, deleted_at, nombre, localidad_id) VALUES (8, true, '2015-05-11 15:07:25', NULL, 'Jamundi', 2);


--
-- TOC entry 2282 (class 0 OID 0)
-- Dependencies: 178
-- Name: localidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('localidad_id_seq', 8, true);


--
-- TOC entry 2225 (class 0 OID 17022)
-- Dependencies: 197
-- Data for Name: negocio; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2283 (class 0 OID 0)
-- Dependencies: 179
-- Name: negocio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('negocio_id_seq', 1, false);


--
-- TOC entry 2226 (class 0 OID 17033)
-- Dependencies: 198
-- Data for Name: paz_y_salvo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2284 (class 0 OID 0)
-- Dependencies: 180
-- Name: paz_y_salvo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('paz_y_salvo_id_seq', 1, false);


--
-- TOC entry 2227 (class 0 OID 17044)
-- Dependencies: 199
-- Data for Name: planilla; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2285 (class 0 OID 0)
-- Dependencies: 181
-- Name: planilla_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('planilla_id_seq', 1, false);


--
-- TOC entry 2228 (class 0 OID 17055)
-- Dependencies: 200
-- Data for Name: prestamo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2286 (class 0 OID 0)
-- Dependencies: 182
-- Name: prestamo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('prestamo_id_seq', 1, false);


--
-- TOC entry 2229 (class 0 OID 17063)
-- Dependencies: 201
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2287 (class 0 OID 0)
-- Dependencies: 186
-- Name: sesion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('sesion_id_seq', 1, false);


--
-- TOC entry 2230 (class 0 OID 17070)
-- Dependencies: 202
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO tipo_documento (id, actived, created_at, deleted_at, desc_documento) VALUES (1, true, '2015-05-11 19:15:48', NULL, 'Cedula');


--
-- TOC entry 2288 (class 0 OID 0)
-- Dependencies: 183
-- Name: tipo_documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_documento_id_seq', 1, false);


--
-- TOC entry 2231 (class 0 OID 17078)
-- Dependencies: 203
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario (id, actived, created_at, deleted_at, user_name, password, last_login_at) VALUES (1, true, '2015-04-06 15:36:14.496', NULL, 'admin', '202cb962ac59075b964b07152d234b70', '2015-07-29 20:38:30');


--
-- TOC entry 2232 (class 0 OID 17088)
-- Dependencies: 204
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario_credencial (id, created_at, usuario_id, credencial_id) VALUES (1, '2015-04-06 15:36:14.496', 1, 1);


--
-- TOC entry 2289 (class 0 OID 0)
-- Dependencies: 187
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- TOC entry 2290 (class 0 OID 0)
-- Dependencies: 188
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 1, true);


--
-- TOC entry 2032 (class 2606 OID 16949)
-- Name: pkbarrio; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY barrio
    ADD CONSTRAINT pkbarrio PRIMARY KEY (id);


--
-- TOC entry 2034 (class 2606 OID 16959)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2069 (class 2606 OID 24583)
-- Name: pkcargo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY cargo
    ADD CONSTRAINT pkcargo PRIMARY KEY (id);


--
-- TOC entry 2037 (class 2606 OID 16978)
-- Name: pkcliente; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT pkcliente PRIMARY KEY (id);


--
-- TOC entry 2039 (class 2606 OID 16987)
-- Name: pkcodeudor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT pkcodeudor PRIMARY KEY (id);


--
-- TOC entry 2041 (class 2606 OID 16995)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2044 (class 2606 OID 17003)
-- Name: pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY (id);


--
-- TOC entry 2046 (class 2606 OID 17013)
-- Name: pkformato_de_prestamo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY formato_de_prestamo
    ADD CONSTRAINT pkformato_de_prestamo PRIMARY KEY (id);


--
-- TOC entry 2048 (class 2606 OID 17021)
-- Name: pklocalidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT pklocalidad PRIMARY KEY (id);


--
-- TOC entry 2050 (class 2606 OID 17032)
-- Name: pknegocio; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY negocio
    ADD CONSTRAINT pknegocio PRIMARY KEY (id);


--
-- TOC entry 2052 (class 2606 OID 17043)
-- Name: pkpaz_y_salvo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY paz_y_salvo
    ADD CONSTRAINT pkpaz_y_salvo PRIMARY KEY (id);


--
-- TOC entry 2054 (class 2606 OID 17054)
-- Name: pkplanilla; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT pkplanilla PRIMARY KEY (id);


--
-- TOC entry 2056 (class 2606 OID 17062)
-- Name: pkprestamo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY prestamo
    ADD CONSTRAINT pkprestamo PRIMARY KEY (id);


--
-- TOC entry 2058 (class 2606 OID 17069)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2060 (class 2606 OID 17077)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2062 (class 2606 OID 17085)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2066 (class 2606 OID 17094)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2035 (class 1259 OID 16979)
-- Name: cliente_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "cliente_usuario_id_Idx" ON cliente USING btree (usuario_id);


--
-- TOC entry 2042 (class 1259 OID 17004)
-- Name: empleado_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "empleado_usuario_id_Idx" ON empleado USING btree (usuario_id);


--
-- TOC entry 2067 (class 1259 OID 17095)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2063 (class 1259 OID 17086)
-- Name: usuario_usuario_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_usuario_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2064 (class 1259 OID 17087)
-- Name: usuario_usuario_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_usuario_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2070 (class 2606 OID 17096)
-- Name: fk_barrio_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY barrio
    ADD CONSTRAINT fk_barrio_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2071 (class 2606 OID 17101)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2072 (class 2606 OID 17106)
-- Name: fk_cliente_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2073 (class 2606 OID 17111)
-- Name: fk_cliente_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2074 (class 2606 OID 17116)
-- Name: fk_cliente_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2075 (class 2606 OID 17121)
-- Name: fk_codeudor_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT fk_codeudor_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2076 (class 2606 OID 17126)
-- Name: fk_codeudor_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT fk_codeudor_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id);


--
-- TOC entry 2078 (class 2606 OID 24584)
-- Name: fk_empleado_cargo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_cargo FOREIGN KEY (cargo_id) REFERENCES cargo(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2077 (class 2606 OID 17136)
-- Name: fk_empleado_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2079 (class 2606 OID 17141)
-- Name: fk_formato_de_prestamo_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY formato_de_prestamo
    ADD CONSTRAINT fk_formato_de_prestamo_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2080 (class 2606 OID 17146)
-- Name: fk_formato_de_prestamo_codeudor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY formato_de_prestamo
    ADD CONSTRAINT fk_formato_de_prestamo_codeudor FOREIGN KEY (codeudor_id) REFERENCES codeudor(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2081 (class 2606 OID 17151)
-- Name: fk_localidad_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT fk_localidad_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2082 (class 2606 OID 17156)
-- Name: fk_negosio_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY negocio
    ADD CONSTRAINT fk_negosio_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2083 (class 2606 OID 17161)
-- Name: fk_paz_y_salvo_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY paz_y_salvo
    ADD CONSTRAINT fk_paz_y_salvo_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2084 (class 2606 OID 17166)
-- Name: fk_planilla_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT fk_planilla_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2085 (class 2606 OID 17171)
-- Name: fk_planilla_prestamo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT fk_planilla_prestamo FOREIGN KEY (prestamo_id) REFERENCES prestamo(id);


--
-- TOC entry 2086 (class 2606 OID 17176)
-- Name: fk_prestamo_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY prestamo
    ADD CONSTRAINT fk_prestamo_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id);


--
-- TOC entry 2087 (class 2606 OID 17181)
-- Name: fk_prestamo_formato_de_prestamo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY prestamo
    ADD CONSTRAINT fk_prestamo_formato_de_prestamo FOREIGN KEY (formato_de_prestamo_id) REFERENCES formato_de_prestamo(id);


--
-- TOC entry 2088 (class 2606 OID 17186)
-- Name: fk_sesion_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_sesion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2089 (class 2606 OID 17191)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2090 (class 2606 OID 17196)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2239 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-07-29 21:33:17

--
-- PostgreSQL database dump complete
--

