--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.5
-- Dumped by pg_dump version 9.3.5
-- Started on 2015-09-03 17:11:04 COT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 204 (class 3079 OID 12018)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2444 (class 0 OID 0)
-- Dependencies: 204
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 191 (class 1259 OID 28755)
-- Name: banco_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE banco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.banco_id_seq OWNER TO postgres;

--
-- TOC entry 2445 (class 0 OID 0)
-- Dependencies: 191
-- Name: SEQUENCE banco_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE banco_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 192 (class 1259 OID 28757)
-- Name: banco; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE banco (
    id bigint DEFAULT nextval('banco_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.banco OWNER TO postgres;

--
-- TOC entry 170 (class 1259 OID 28452)
-- Name: barrio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE barrio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.barrio_id_seq OWNER TO postgres;

--
-- TOC entry 2446 (class 0 OID 0)
-- Dependencies: 170
-- Name: SEQUENCE barrio_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE barrio_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 193 (class 1259 OID 28764)
-- Name: barrio; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE barrio (
    id integer DEFAULT nextval('barrio_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre_barrio character varying(50) NOT NULL,
    localidad_id integer
);


ALTER TABLE public.barrio OWNER TO postgres;

--
-- TOC entry 2447 (class 0 OID 0)
-- Dependencies: 193
-- Name: COLUMN barrio.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN barrio.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 171 (class 1259 OID 28460)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2448 (class 0 OID 0)
-- Dependencies: 171
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 172 (class 1259 OID 28462)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id integer DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    fecha timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    accion character varying(50) NOT NULL,
    observacion character varying(1024),
    tabla character varying(65) NOT NULL,
    registro bigint
);


ALTER TABLE public.bitacora OWNER TO postgres;

--
-- TOC entry 173 (class 1259 OID 28478)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.cliente_id_seq OWNER TO postgres;

--
-- TOC entry 2449 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE cliente_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE cliente_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 194 (class 1259 OID 28772)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE cliente (
    id integer DEFAULT nextval('cliente_id_seq'::regclass) NOT NULL,
    usuario_id integer NOT NULL,
    localidad_id integer NOT NULL,
    tipo_documento_id integer NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    identificacion character varying(100) NOT NULL,
    nombre character varying(60) NOT NULL,
    apellidos character varying(60) NOT NULL,
    celular character varying(12),
    telefono character varying(15) NOT NULL,
    correo character varying(100) NOT NULL,
    direccion character varying(200) NOT NULL,
    fecha_nacimiento date NOT NULL
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 2450 (class 0 OID 0)
-- Dependencies: 194
-- Name: COLUMN cliente.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN cliente.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 174 (class 1259 OID 28489)
-- Name: codeudor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE codeudor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.codeudor_id_seq OWNER TO postgres;

--
-- TOC entry 2451 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE codeudor_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE codeudor_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 195 (class 1259 OID 28784)
-- Name: codeudor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE codeudor (
    id integer DEFAULT nextval('codeudor_id_seq'::regclass) NOT NULL,
    localidad_id integer NOT NULL,
    tipo_documento_id integer NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    identificacion integer NOT NULL,
    nombre character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    telefono character varying(15) NOT NULL,
    movil character varying(13),
    direccion character varying(100) NOT NULL,
    correo character varying(60) NOT NULL
);


ALTER TABLE public.codeudor OWNER TO postgres;

--
-- TOC entry 2452 (class 0 OID 0)
-- Dependencies: 195
-- Name: COLUMN codeudor.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN codeudor.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 175 (class 1259 OID 28497)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2453 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 176 (class 1259 OID 28499)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id integer DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.credencial OWNER TO postgres;

--
-- TOC entry 2454 (class 0 OID 0)
-- Dependencies: 176
-- Name: COLUMN credencial.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN credencial.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 177 (class 1259 OID 28505)
-- Name: empleado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.empleado_id_seq OWNER TO postgres;

--
-- TOC entry 2455 (class 0 OID 0)
-- Dependencies: 177
-- Name: SEQUENCE empleado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE empleado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 196 (class 1259 OID 28792)
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE empleado (
    id integer DEFAULT nextval('empleado_id_seq'::regclass) NOT NULL,
    usuario_id integer NOT NULL,
    tipo_documento_id integer,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    identificacion character varying(100) NOT NULL,
    nombre character varying(50) NOT NULL,
    apellidos character varying(50) NOT NULL,
    direccion character varying(50) NOT NULL,
    telefono character varying(15) NOT NULL,
    movil character varying(12) NOT NULL,
    correo character varying(100) NOT NULL
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- TOC entry 2456 (class 0 OID 0)
-- Dependencies: 196
-- Name: COLUMN empleado.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN empleado.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 178 (class 1259 OID 28513)
-- Name: formato_de_prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE formato_de_prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.formato_de_prestamo_id_seq OWNER TO postgres;

--
-- TOC entry 2457 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE formato_de_prestamo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE formato_de_prestamo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 197 (class 1259 OID 28801)
-- Name: formato_prestamo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE formato_prestamo (
    id integer DEFAULT nextval('formato_de_prestamo_id_seq'::regclass) NOT NULL,
    cliente_id integer NOT NULL,
    codeudor_id integer NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    monto_capital integer NOT NULL,
    numero_cuotas integer NOT NULL,
    banco_id bigint NOT NULL,
    tipo_cuenta_bancaria boolean NOT NULL,
    num_cuenta_bancaria character varying(30) NOT NULL,
    aprovado boolean DEFAULT false,
    latitud character varying(100) NOT NULL,
    longitud character varying(100) NOT NULL
);


ALTER TABLE public.formato_prestamo OWNER TO postgres;

--
-- TOC entry 2458 (class 0 OID 0)
-- Dependencies: 197
-- Name: COLUMN formato_prestamo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN formato_prestamo.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 2459 (class 0 OID 0)
-- Dependencies: 197
-- Name: COLUMN formato_prestamo.tipo_cuenta_bancaria; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN formato_prestamo.tipo_cuenta_bancaria IS 't = ahorro | f = corriente';


--
-- TOC entry 2460 (class 0 OID 0)
-- Dependencies: 197
-- Name: COLUMN formato_prestamo.aprovado; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN formato_prestamo.aprovado IS 'FALSE = no aprovado | TRUE = aprobado';


--
-- TOC entry 179 (class 1259 OID 28522)
-- Name: localidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE localidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.localidad_id_seq OWNER TO postgres;

--
-- TOC entry 2461 (class 0 OID 0)
-- Dependencies: 179
-- Name: SEQUENCE localidad_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE localidad_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 198 (class 1259 OID 28810)
-- Name: localidad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE localidad (
    id integer DEFAULT nextval('localidad_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(50) NOT NULL,
    localidad_id integer
);


ALTER TABLE public.localidad OWNER TO postgres;

--
-- TOC entry 2462 (class 0 OID 0)
-- Dependencies: 198
-- Name: COLUMN localidad.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN localidad.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 180 (class 1259 OID 28530)
-- Name: negocio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE negocio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.negocio_id_seq OWNER TO postgres;

--
-- TOC entry 2463 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE negocio_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE negocio_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 199 (class 1259 OID 28818)
-- Name: negocio; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE negocio (
    id integer DEFAULT nextval('negocio_id_seq'::regclass) NOT NULL,
    cliente_id integer NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    nombre character varying(1024) NOT NULL,
    direccion character varying(100) NOT NULL,
    telefono character varying(15) NOT NULL,
    ingresos_mensual numeric(12,0) NOT NULL
);


ALTER TABLE public.negocio OWNER TO postgres;

--
-- TOC entry 2464 (class 0 OID 0)
-- Dependencies: 199
-- Name: COLUMN negocio.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN negocio.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 181 (class 1259 OID 28541)
-- Name: paz_y_salvo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE paz_y_salvo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.paz_y_salvo_id_seq OWNER TO postgres;

--
-- TOC entry 2465 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE paz_y_salvo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE paz_y_salvo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 200 (class 1259 OID 28829)
-- Name: paz_y_salvo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE paz_y_salvo (
    id bigint DEFAULT nextval('paz_y_salvo_id_seq'::regclass) NOT NULL,
    prestamo_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    pdf character varying(37) NOT NULL
);


ALTER TABLE public.paz_y_salvo OWNER TO postgres;

--
-- TOC entry 182 (class 1259 OID 28552)
-- Name: planilla_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE planilla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.planilla_id_seq OWNER TO postgres;

--
-- TOC entry 2466 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE planilla_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE planilla_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 201 (class 1259 OID 28836)
-- Name: planilla; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE planilla (
    id integer DEFAULT nextval('planilla_id_seq'::regclass) NOT NULL,
    empleado_id integer,
    prestamo_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    fecha_recogida date,
    valor_recaudo integer DEFAULT 0 NOT NULL,
    observaciones character varying(1024),
    latitud character varying(100),
    longitud character varying(100)
);


ALTER TABLE public.planilla OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 28563)
-- Name: prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.prestamo_id_seq OWNER TO postgres;

--
-- TOC entry 2467 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE prestamo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE prestamo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 28847)
-- Name: prestamo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE prestamo (
    id integer DEFAULT nextval('prestamo_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    formato_de_prestamo_id integer NOT NULL,
    tiempo_cuota integer NOT NULL,
    monto_cuota bigint NOT NULL,
    fecha_inicio date NOT NULL
);


ALTER TABLE public.prestamo OWNER TO postgres;

--
-- TOC entry 2468 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN prestamo.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.actived IS 'true = activo | false = inactivo';


--
-- TOC entry 2469 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN prestamo.tiempo_cuota; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.tiempo_cuota IS 'Cada cauntos días se recoge el dinero';


--
-- TOC entry 2470 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN prestamo.monto_cuota; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.monto_cuota IS 'Cuanto se recoge por cuota';


--
-- TOC entry 2471 (class 0 OID 0)
-- Dependencies: 202
-- Name: COLUMN prestamo.fecha_inicio; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN prestamo.fecha_inicio IS 'Cuando empieza la deuda';


--
-- TOC entry 184 (class 1259 OID 28571)
-- Name: sesion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE sesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sesion_id_seq OWNER TO postgres;

--
-- TOC entry 2472 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE sesion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE sesion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 185 (class 1259 OID 28573)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id integer DEFAULT nextval('sesion_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    ip_address character varying(36) NOT NULL
);


ALTER TABLE public.recordar_me OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 28578)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tipo_documento_id_seq OWNER TO postgres;

--
-- TOC entry 2473 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 28855)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_documento (
    id integer DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    desc_documento character varying(100) NOT NULL
);


ALTER TABLE public.tipo_documento OWNER TO postgres;

--
-- TOC entry 2474 (class 0 OID 0)
-- Dependencies: 203
-- Name: COLUMN tipo_documento.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN tipo_documento.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 187 (class 1259 OID 28586)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2475 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 188 (class 1259 OID 28588)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id integer DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone,
    user_name character varying(50) NOT NULL,
    password character varying(32) NOT NULL,
    last_login_at timestamp without time zone
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 2476 (class 0 OID 0)
-- Dependencies: 188
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'true = activo ; false = desactivado';


--
-- TOC entry 189 (class 1259 OID 28594)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2477 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 190 (class 1259 OID 28596)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id integer DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    usuario_id integer NOT NULL,
    credencial_id integer NOT NULL
);


ALTER TABLE public.usuario_credencial OWNER TO postgres;

--
-- TOC entry 2425 (class 0 OID 28757)
-- Dependencies: 192
-- Data for Name: banco; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2478 (class 0 OID 0)
-- Dependencies: 191
-- Name: banco_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('banco_id_seq', 1, false);


--
-- TOC entry 2426 (class 0 OID 28764)
-- Dependencies: 193
-- Data for Name: barrio; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2479 (class 0 OID 0)
-- Dependencies: 170
-- Name: barrio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('barrio_id_seq', 3, true);


--
-- TOC entry 2405 (class 0 OID 28462)
-- Dependencies: 172
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO bitacora (id, fecha, usuario_id, accion, observacion, tabla, registro) VALUES (47, '2015-09-03 22:27:46', 1, 'identificacion', NULL, 'NINGUNA', NULL);


--
-- TOC entry 2480 (class 0 OID 0)
-- Dependencies: 171
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 47, true);


--
-- TOC entry 2427 (class 0 OID 28772)
-- Dependencies: 194
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2481 (class 0 OID 0)
-- Dependencies: 173
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('cliente_id_seq', 8, true);


--
-- TOC entry 2428 (class 0 OID 28784)
-- Dependencies: 195
-- Data for Name: codeudor; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2482 (class 0 OID 0)
-- Dependencies: 174
-- Name: codeudor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('codeudor_id_seq', 1, false);


--
-- TOC entry 2409 (class 0 OID 28499)
-- Dependencies: 176
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO credencial (id, actived, created_at, deleted_at, nombre) VALUES (1, true, '2015-04-06 15:36:14.496', NULL, 'admin');
INSERT INTO credencial (id, actived, created_at, deleted_at, nombre) VALUES (3, true, '2015-09-03 16:05:00.078653', NULL, 'cobrador');
INSERT INTO credencial (id, actived, created_at, deleted_at, nombre) VALUES (2, true, '2015-04-06 15:36:14.496', NULL, 'cliente');


--
-- TOC entry 2483 (class 0 OID 0)
-- Dependencies: 175
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 4, true);


--
-- TOC entry 2429 (class 0 OID 28792)
-- Dependencies: 196
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2484 (class 0 OID 0)
-- Dependencies: 177
-- Name: empleado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('empleado_id_seq', 2, true);


--
-- TOC entry 2485 (class 0 OID 0)
-- Dependencies: 178
-- Name: formato_de_prestamo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('formato_de_prestamo_id_seq', 1, false);


--
-- TOC entry 2430 (class 0 OID 28801)
-- Dependencies: 197
-- Data for Name: formato_prestamo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2431 (class 0 OID 28810)
-- Dependencies: 198
-- Data for Name: localidad; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2486 (class 0 OID 0)
-- Dependencies: 179
-- Name: localidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('localidad_id_seq', 8, true);


--
-- TOC entry 2432 (class 0 OID 28818)
-- Dependencies: 199
-- Data for Name: negocio; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2487 (class 0 OID 0)
-- Dependencies: 180
-- Name: negocio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('negocio_id_seq', 1, false);


--
-- TOC entry 2433 (class 0 OID 28829)
-- Dependencies: 200
-- Data for Name: paz_y_salvo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2488 (class 0 OID 0)
-- Dependencies: 181
-- Name: paz_y_salvo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('paz_y_salvo_id_seq', 1, false);


--
-- TOC entry 2434 (class 0 OID 28836)
-- Dependencies: 201
-- Data for Name: planilla; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2489 (class 0 OID 0)
-- Dependencies: 182
-- Name: planilla_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('planilla_id_seq', 1, false);


--
-- TOC entry 2435 (class 0 OID 28847)
-- Dependencies: 202
-- Data for Name: prestamo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2490 (class 0 OID 0)
-- Dependencies: 183
-- Name: prestamo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('prestamo_id_seq', 1, false);


--
-- TOC entry 2418 (class 0 OID 28573)
-- Dependencies: 185
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2491 (class 0 OID 0)
-- Dependencies: 184
-- Name: sesion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('sesion_id_seq', 1, false);


--
-- TOC entry 2436 (class 0 OID 28855)
-- Dependencies: 203
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2492 (class 0 OID 0)
-- Dependencies: 186
-- Name: tipo_documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_documento_id_seq', 1, false);


--
-- TOC entry 2421 (class 0 OID 28588)
-- Dependencies: 188
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario (id, actived, created_at, deleted_at, user_name, password, last_login_at) VALUES (2, true, '2015-08-22 12:26:13.238', NULL, 'maloca', 'b53086d558f1127993271e8c504ded45', NULL);
INSERT INTO usuario (id, actived, created_at, deleted_at, user_name, password, last_login_at) VALUES (1, true, '2015-04-06 15:36:14.496', NULL, 'admin', '202cb962ac59075b964b07152d234b70', '2015-09-03 22:27:46');


--
-- TOC entry 2423 (class 0 OID 28596)
-- Dependencies: 190
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario_credencial (id, created_at, usuario_id, credencial_id) VALUES (1, '2015-04-06 15:36:14.496', 1, 1);


--
-- TOC entry 2493 (class 0 OID 0)
-- Dependencies: 189
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- TOC entry 2494 (class 0 OID 0)
-- Dependencies: 187
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 2, true);


--
-- TOC entry 2250 (class 2606 OID 28763)
-- Name: pkbanco; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY banco
    ADD CONSTRAINT pkbanco PRIMARY KEY (id);


--
-- TOC entry 2252 (class 2606 OID 28771)
-- Name: pkbarrio; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY barrio
    ADD CONSTRAINT pkbarrio PRIMARY KEY (id);


--
-- TOC entry 2237 (class 2606 OID 28604)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2255 (class 2606 OID 28782)
-- Name: pkcliente; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT pkcliente PRIMARY KEY (id);


--
-- TOC entry 2257 (class 2606 OID 28791)
-- Name: pkcodeudor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT pkcodeudor PRIMARY KEY (id);


--
-- TOC entry 2239 (class 2606 OID 28612)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2260 (class 2606 OID 28799)
-- Name: pkempleado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT pkempleado PRIMARY KEY (id);


--
-- TOC entry 2262 (class 2606 OID 28809)
-- Name: pkformato_prestamo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY formato_prestamo
    ADD CONSTRAINT pkformato_prestamo PRIMARY KEY (id);


--
-- TOC entry 2264 (class 2606 OID 28817)
-- Name: pklocalidad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT pklocalidad PRIMARY KEY (id);


--
-- TOC entry 2266 (class 2606 OID 28828)
-- Name: pknegocio; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY negocio
    ADD CONSTRAINT pknegocio PRIMARY KEY (id);


--
-- TOC entry 2268 (class 2606 OID 28835)
-- Name: pkpaz_y_salvo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY paz_y_salvo
    ADD CONSTRAINT pkpaz_y_salvo PRIMARY KEY (id);


--
-- TOC entry 2270 (class 2606 OID 28846)
-- Name: pkplanilla; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT pkplanilla PRIMARY KEY (id);


--
-- TOC entry 2272 (class 2606 OID 28854)
-- Name: pkprestamo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY prestamo
    ADD CONSTRAINT pkprestamo PRIMARY KEY (id);


--
-- TOC entry 2241 (class 2606 OID 28628)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2274 (class 2606 OID 28862)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2243 (class 2606 OID 28632)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2247 (class 2606 OID 28634)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2253 (class 1259 OID 28783)
-- Name: cliente_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "cliente_usuario_id_Idx" ON cliente USING btree (usuario_id);


--
-- TOC entry 2258 (class 1259 OID 28800)
-- Name: empleado_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "empleado_usuario_id_Idx" ON empleado USING btree (usuario_id);


--
-- TOC entry 2248 (class 1259 OID 28637)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2244 (class 1259 OID 28638)
-- Name: usuario_usuario_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_usuario_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2245 (class 1259 OID 28639)
-- Name: usuario_usuario_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_usuario_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2279 (class 2606 OID 28863)
-- Name: fk_barrio_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY barrio
    ADD CONSTRAINT fk_barrio_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2275 (class 2606 OID 28645)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2280 (class 2606 OID 28868)
-- Name: fk_cliente_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2281 (class 2606 OID 28873)
-- Name: fk_cliente_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2282 (class 2606 OID 28878)
-- Name: fk_cliente_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY cliente
    ADD CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2283 (class 2606 OID 28883)
-- Name: fk_codeudor_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT fk_codeudor_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2284 (class 2606 OID 28888)
-- Name: fk_codeudor_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY codeudor
    ADD CONSTRAINT fk_codeudor_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id);


--
-- TOC entry 2285 (class 2606 OID 28893)
-- Name: fk_empleado_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_tipo_documento FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento(id);


--
-- TOC entry 2286 (class 2606 OID 28898)
-- Name: fk_empleado_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY empleado
    ADD CONSTRAINT fk_empleado_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2287 (class 2606 OID 28903)
-- Name: fk_formato_de_prestamo_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY formato_prestamo
    ADD CONSTRAINT fk_formato_de_prestamo_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2288 (class 2606 OID 28908)
-- Name: fk_formato_de_prestamo_codeudor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY formato_prestamo
    ADD CONSTRAINT fk_formato_de_prestamo_codeudor FOREIGN KEY (codeudor_id) REFERENCES codeudor(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2289 (class 2606 OID 28913)
-- Name: fk_formato_prestamo_banco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY formato_prestamo
    ADD CONSTRAINT fk_formato_prestamo_banco FOREIGN KEY (banco_id) REFERENCES banco(id);


--
-- TOC entry 2290 (class 2606 OID 28918)
-- Name: fk_localidad_localidad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY localidad
    ADD CONSTRAINT fk_localidad_localidad FOREIGN KEY (localidad_id) REFERENCES localidad(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2291 (class 2606 OID 28923)
-- Name: fk_negosio_cliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY negocio
    ADD CONSTRAINT fk_negosio_cliente FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2292 (class 2606 OID 28928)
-- Name: fk_paz_y_salvo_prestamo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY paz_y_salvo
    ADD CONSTRAINT fk_paz_y_salvo_prestamo FOREIGN KEY (prestamo_id) REFERENCES prestamo(id);


--
-- TOC entry 2293 (class 2606 OID 28933)
-- Name: fk_planilla_empleado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT fk_planilla_empleado FOREIGN KEY (empleado_id) REFERENCES empleado(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2294 (class 2606 OID 28938)
-- Name: fk_planilla_prestamo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY planilla
    ADD CONSTRAINT fk_planilla_prestamo FOREIGN KEY (prestamo_id) REFERENCES prestamo(id);


--
-- TOC entry 2295 (class 2606 OID 28943)
-- Name: fk_prestamo_formato_de_prestamo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY prestamo
    ADD CONSTRAINT fk_prestamo_formato_de_prestamo FOREIGN KEY (formato_de_prestamo_id) REFERENCES formato_prestamo(id);


--
-- TOC entry 2276 (class 2606 OID 28730)
-- Name: fk_sesion_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_sesion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2277 (class 2606 OID 28735)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2278 (class 2606 OID 28740)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2443 (class 0 OID 0)
-- Dependencies: 6
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-09-03 17:11:04 COT

--
-- PostgreSQL database dump complete
--

